[package]
name = "emu"
version = "0.5.0"
authors = ["İsmail Dönmez <ismail@i10z.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
num-derive = "0.3"

[profile.release]
lto = true
panic = 'abort'
