[package]
name = "arm-emu"
version = "0.1.0"
authors = ["İsmail Dönmez <ismail@i10z.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
