[package]
name = "emu"
version = "0.6.0"
authors = ["İsmail Dönmez <ismail@i10z.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
num-traits = "0.2"
num-derive = "0.3"

[profile.release]
lto = true
panic = 'abort'
