name: Build Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ismail/rust-action@main
        with:
          args: RUSTFLAGS='-C link-arg=-s' cargo build --target x86_64-unknown-linux-musl --release
